server:
  port: 8080

spring:
  application:
    name: redis-demo
  redis:
    host: localhost
    port: 6379
    timeout: 600000
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: 100000


logging:
  level:
    root: info
    com:
      ningdr:
        redis:
          jedis:
            demo: debug
